spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_IP}:${POSTGRES_PORT}/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_URL}

server:
  port: ${PORT}

topic:
  name: ${TOPIC_NAME}
  groupId: ${KAFKA_GROUP_ID}

client:
  user-service : ${USER-SERVICE_URL}
