spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  application:
    name: gateway-service
  cloud:
    gateway:
        routes:
          - id: user-service-register
            uri: http://localhost:8010
            predicates: Path=/api/v1/auth/register
          - id: user-service-login
            uri: http://localhost:8010
            predicates: Path=/api/v1/auth/login
          - id: create-order
            uri: http://localhost:8020
            predicates: Path=/api/v1/order/create-order
            filters: OrderServiceFilter
          - id: get-order
            uri: ttp://localhost:8020
            predicates: Path=/api/v1/order/get-order
            filters: OrderServiceFilter
  data:
    redis:
      host: localhost
      port: 6379
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt:
  secret: 81CE856A12266386CE88518C4343881CE856A12266386CE88518C4343881CE856A12266386CE88518C43438
server:
  port: 8100
